apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-deployment
  namespace: test-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1             # or "50%" for percentage
      maxUnavailable: 1       # or "50%" for percentage
  minReadySeconds: 30
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      name: pod-chatapp
      labels:
        app: chatapp
    spec:
      containers:
        - name: chatapp-container
          image: chaitanyavamsi/chatapp:v1
          ports:
           - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: chatapp
  ports:
    - port: 81
      targetPort: 3000
      nodePort: 32252
