apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-deplyment
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      name: pod-chatapp
      labels:
        app: chatapp
    spec:
      containers:
        - name: chatapp-conatiner
          image: chaitanyavamsi/chatapp:v1
          ports:
           - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: chatapp
  ports:
    - port: 81
      targetPort: 3000
      nodePort: 32252